server:
  port: 8080

spring:
  datasource:
  #  url: jdbc:mysql://cobol.idlab.ugent.be:3306/auth?useLegacyDatetimeCode=false&serverTimezone=UTC
  #  username: www
  #  password: cobol2020

    url: jdbc:mysql://localhost:3306/auth?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Bach&Proef88


#    cachePrepStmts: true
#    prepStmtCacheSize: 250
#    prepStmtCacheSqlLimit: 2048
#    useServerPrepStmts: true

#  jackson:
#    mapper:
#      DEFAULT_VIEW_INCLUSION: true
#    serialization:
#      indent_output: true
#      WRITE_DATES_AS_TIMESTAMPS: false
#    deserialization:
#      FAIL_ON_IGNORED_PROPERTIES: false
#      FAIL_ON_UNKNOWN_PROPERTIES: false
#      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
#    default-property-inclusion: non_empty

  jpa:
    show_sql: true
#    openInView: false
#    generate-ddl: true
    hibernate:
      ddl-auto: create #-drop

#  data:
#    jpa:
#      repositories.enabled: true
#
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    cobol: DEBUG
  file:
    name: app.log
